server:
  port: 8080

logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/currency_fair?serverTimezone=GMT
  h2:
    console:
      enabled: false
