server:
  port: 8080

logging:
  level:
    root: info
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p})  %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    path: /logs
    name: application.log

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/currency_fair?serverTimezone=GMT # To be defined